# Generated by Django 3.0 on 2021-03-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='texto',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
