# Generated by Django 3.0 on 2021-03-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_novedad_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='texto',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
