# Generated by Django 3.0 on 2021-03-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novedades', '0003_auto_20210309_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedad',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novedad',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='texto',
            field=models.TextField(),
        ),
    ]
