# Generated by Django 3.0 on 2021-03-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0005_auto_20210310_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedad',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
