# Generated by Django 3.0 on 2021-03-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0007_novedad_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='created_date',
        ),
    ]
