# Generated by Django 3.0 on 2021-03-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0009_novedad_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(null=True, upload_to='novedades'),
        ),
        migrations.AlterField(
            model_name='novedad',
            name='published_date',
            field=models.DateTimeField(),
        ),
    ]
