# Generated by Django 3.0 on 2021-03-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0011_auto_20210311_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='novedades'),
        ),
    ]
