# Generated by Django 3.0 on 2021-03-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0012_auto_20210311_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='imagen',
            field=models.ImageField(upload_to='novedades'),
        ),
    ]
