# Generated by Django 3.0 on 2021-03-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0015_auto_20210312_2048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='text',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='approved_comment',
        ),
    ]
