# Generated by Django 3.0 on 2021-03-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0016_auto_20210312_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novedad',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Filtro_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novedades.Categoria')),
            ],
        ),
    ]
